import type { FC } from 'react';
import type { SvgProps } from 'react-native-svg';

/**
 * Static illustration assets for each 5-bit Binary Mode pattern.
 * Generated by scripts/generate_binary_gesture_illustrations.py
 *
 * Finger order: Thumb, Index, Middle, Ring, Pinky
 */
export const BINARY_PATTERN_BITS = [
  '00000', '00001', '00010', '00011', '00100', '00101', '00110', '00111',
  '01000', '01001', '01010', '01011', '01100', '01101', '01110', '01111',
  '10000', '10001', '10010', '10011', '10100', '10101', '10110', '10111',
  '11000', '11001', '11010', '11011', '11100', '11101', '11110', '11111',
] as const;

export type BinaryPattern = (typeof BINARY_PATTERN_BITS)[number];

export const FINGER_LABELS = ['Thumb', 'Index', 'Middle', 'Ring', 'Pinky'] as const;

type SvgComponent = FC<SvgProps>;

function loadSvg(moduleRef: SvgComponent | { default: SvgComponent }): SvgComponent {
  if (typeof moduleRef === 'function') {
    return moduleRef;
  }

  return moduleRef.default;
}

/** Bundled SVG illustrations keyed by 5-bit pattern. */
export const GESTURE_ILLUSTRATIONS: Record<BinaryPattern, SvgComponent> = {
  '00000': loadSvg(require('../../../assets/binary-gestures/00000.svg')),
  '00001': loadSvg(require('../../../assets/binary-gestures/00001.svg')),
  '00010': loadSvg(require('../../../assets/binary-gestures/00010.svg')),
  '00011': loadSvg(require('../../../assets/binary-gestures/00011.svg')),
  '00100': loadSvg(require('../../../assets/binary-gestures/00100.svg')),
  '00101': loadSvg(require('../../../assets/binary-gestures/00101.svg')),
  '00110': loadSvg(require('../../../assets/binary-gestures/00110.svg')),
  '00111': loadSvg(require('../../../assets/binary-gestures/00111.svg')),
  '01000': loadSvg(require('../../../assets/binary-gestures/01000.svg')),
  '01001': loadSvg(require('../../../assets/binary-gestures/01001.svg')),
  '01010': loadSvg(require('../../../assets/binary-gestures/01010.svg')),
  '01011': loadSvg(require('../../../assets/binary-gestures/01011.svg')),
  '01100': loadSvg(require('../../../assets/binary-gestures/01100.svg')),
  '01101': loadSvg(require('../../../assets/binary-gestures/01101.svg')),
  '01110': loadSvg(require('../../../assets/binary-gestures/01110.svg')),
  '01111': loadSvg(require('../../../assets/binary-gestures/01111.svg')),
  '10000': loadSvg(require('../../../assets/binary-gestures/10000.svg')),
  '10001': loadSvg(require('../../../assets/binary-gestures/10001.svg')),
  '10010': loadSvg(require('../../../assets/binary-gestures/10010.svg')),
  '10011': loadSvg(require('../../../assets/binary-gestures/10011.svg')),
  '10100': loadSvg(require('../../../assets/binary-gestures/10100.svg')),
  '10101': loadSvg(require('../../../assets/binary-gestures/10101.svg')),
  '10110': loadSvg(require('../../../assets/binary-gestures/10110.svg')),
  '10111': loadSvg(require('../../../assets/binary-gestures/10111.svg')),
  '11000': loadSvg(require('../../../assets/binary-gestures/11000.svg')),
  '11001': loadSvg(require('../../../assets/binary-gestures/11001.svg')),
  '11010': loadSvg(require('../../../assets/binary-gestures/11010.svg')),
  '11011': loadSvg(require('../../../assets/binary-gestures/11011.svg')),
  '11100': loadSvg(require('../../../assets/binary-gestures/11100.svg')),
  '11101': loadSvg(require('../../../assets/binary-gestures/11101.svg')),
  '11110': loadSvg(require('../../../assets/binary-gestures/11110.svg')),
  '11111': loadSvg(require('../../../assets/binary-gestures/11111.svg')),
};

export function getGestureIllustration(bits: string): SvgComponent | null {
  if (bits.length !== 5 || !/^[01]{5}$/.test(bits)) return null;
  return GESTURE_ILLUSTRATIONS[bits as BinaryPattern] ?? null;
}

export function formatFingerBits(bits: string): string {
  return FINGER_LABELS.map((label, index) => `${label[0]}:${bits[index] ?? '0'}`).join('  ');
}

export function isBinaryPattern(bits: string): bits is BinaryPattern {
  return bits.length === 5 && /^[01]{5}$/.test(bits) && bits in GESTURE_ILLUSTRATIONS;
}
